### PR TITLE
Multi-Threading!

### PR DESCRIPTION
**Pull request by JonathanBroering**
**This Version is using Multi-Threading!**

The code is mostly the same, but now downloads, unpacks & cleans all the files at the same time. 
Time for the script to complete downloading, unpacking & cleaning has therefor been reduced. 
Using 3 courses, i was able to get the speed from ~90 Seconds down to ~60 Seconds.

### CODE REVIEW

**Comment by JonathanBroering** [comment]
Any plans on mergin the PR? :)

**Comment by JoHoop** [comment]
Good stuff!!

**Comment by JoHoop** [comment]
@all-contributors please add @jnthn-b for Multi-Threading

**Comment by JoHoop** [comment]
@all-contributors please add @jnthn-b for code

**Pull request merged**
